version: "3.7"

services:
  eigenvo:
    build:
      context: .
    image: eigenvo:$VERSION
    container_name: eigenvo
    ports:
      - 8050:8050
    environment:
      - TARGET=$TARGET
      - HOST=$HOST
      - PORT=$PORT
      - DEBUG=$DEBUG
    restart: on-failure